import AVFoundation

enum LaunchSound: String, CaseIterable, Sendable {
    /// Chirping while the pieces fly in.
    case arrival
    /// A pleased tweet as the bird lands and puffs up.
    case hop
    /// Wing beats as it leaves with the receipt.
    case flyaway
}

protocol LaunchSoundPlaying: Sendable {
    /// Loads the clips and activates the audio session. Call before the first `play`
    /// so none of that cost lands mid-animation.
    func prepare() async
    func play(_ sound: LaunchSound) async
    func stop() async
}

/// Plays the splash's effects through the ambient session so they mix with whatever
/// the user already has playing and stay silent when the ringer switch is off.
/// Sounds are generated by `design/launch-sounds.py`.
///
/// An actor rather than a main-actor class: activating the session and decoding the
/// files take long enough on a device to drop frames if done on the main thread.
actor LaunchSoundPlayer: LaunchSoundPlaying {
    private var players: [LaunchSound: AVAudioPlayer] = [:]

    func prepare() async {
        guard players.isEmpty else { return }
        do {
            let session = AVAudioSession.sharedInstance()
            try session.setCategory(.ambient, options: .mixWithOthers)
            try session.setActive(true)
        } catch {
            AppLog.error(error, "Launch sounds: audio session")
        }
        for sound in LaunchSound.allCases {
            guard let url = Bundle.main.url(forResource: sound.rawValue, withExtension: "caf") else {
                continue
            }
            do {
                let player = try AVAudioPlayer(contentsOf: url)
                player.prepareToPlay()
                players[sound] = player
            } catch {
                AppLog.error(error, "Launch sounds: \(sound.rawValue)")
            }
        }
    }

    func play(_ sound: LaunchSound) {
        guard let player = players[sound] else { return }
        player.currentTime = 0
        player.play()
    }

    func stop() {
        for player in players.values {
            player.stop()
        }
    }
}
