import AVFoundation

enum LaunchSound: String, CaseIterable, Sendable {
    /// The bird's opening remark, timed with its hop.
    case squawk
    /// Wing flaps and a parting call as it leaves with the receipt.
    case flyaway
}

protocol LaunchSoundPlaying {
    func play(_ sound: LaunchSound)
    func stop()
}

/// Plays the splash's effects through the ambient session so they mix with whatever
/// the user already has playing and stay silent when the ringer switch is off.
/// Sounds are generated by `design/launch-sounds.py`.
final class LaunchSoundPlayer: LaunchSoundPlaying {
    private var players: [LaunchSound: AVAudioPlayer] = [:]

    init() {
        do {
            try AVAudioSession.sharedInstance().setCategory(.ambient, options: .mixWithOthers)
        } catch {
            AppLog.error(error, "Launch sounds: audio session")
        }
        for sound in LaunchSound.allCases {
            guard let url = Bundle.main.url(forResource: sound.rawValue, withExtension: "caf") else {
                continue
            }
            do {
                let player = try AVAudioPlayer(contentsOf: url)
                player.prepareToPlay()
                players[sound] = player
            } catch {
                AppLog.error(error, "Launch sounds: \(sound.rawValue)")
            }
        }
    }

    func play(_ sound: LaunchSound) {
        guard let player = players[sound] else { return }
        player.currentTime = 0
        player.play()
    }

    func stop() {
        for player in players.values {
            player.stop()
        }
    }
}
